version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: fileupload_postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: filedb
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: fileupload_redis
    restart: always
    ports:
      - "6379:6379"

volumes: {}
